import type { InterestedStudent, Opportunity, Organization } from './types';

/* Seed data for V1. Organizations are invented local businesses and
   nonprofits rather than real brands — nothing here should read as a genuine
   posting from a company that never made one.

   The set is deliberately uneven: postings sit at 15+ through 18+, from half
   a mile to eleven miles out, and one organization is still unverified. That
   is what makes the eligibility panel and the verification gate observable
   instead of theoretical. */

const DAY = 86_400_000;

/* Posting dates are stored as an age in days and resolved at load, so "New
   this week" keeps meaning this week however long the seed sits in the repo. */
const daysBack = (days: number) => new Date(Date.now() - days * DAY).toISOString();

export const ORGANIZATIONS: Organization[] = [
  {
    id: 'org-citrus',
    name: 'Citrus Grove Smoothies',
    kind: 'business',
    verified: true,
    website: 'citrusgrove.example',
    about: 'A six-store smoothie and açaí bar. Most of the team is in high school or just out of it.',
    location: { city: 'Santa Clara', zip: '95050', lat: 37.3512, lng: -121.9556 },
  },
  {
    id: 'org-westgate',
    name: 'Westgate Cinema',
    kind: 'business',
    verified: true,
    about: 'An eight-screen neighbourhood cinema that has been on the same corner since 1974.',
    location: { city: 'San Jose', zip: '95117', lat: 37.3121, lng: -121.9535 },
  },
  {
    id: 'org-paws',
    name: 'Paws & Whiskers Rescue',
    kind: 'nonprofit',
    verified: true,
    about: 'A volunteer-run shelter for cats and small dogs. Around sixty animals at a time.',
    location: { city: 'Campbell', zip: '95008', lat: 37.2872, lng: -121.95 },
  },
  {
    id: 'org-aquatics',
    name: 'South Bay Aquatics',
    kind: 'business',
    verified: true,
    about: 'Swim school for toddlers through teens. Two heated pools, open year-round.',
    location: { city: 'Sunnyvale', zip: '94086', lat: 37.3752, lng: -122.0221 },
  },
  {
    id: 'org-bayline',
    name: 'Bayline Community Food Bank',
    kind: 'nonprofit',
    verified: true,
    about: 'Packs and distributes about 9,000 grocery boxes a month across the county.',
    location: { city: 'San Jose', zip: '95110', lat: 37.3382, lng: -121.8936 },
  },
  {
    id: 'org-riverbend',
    name: 'Riverbend Dental Studio',
    kind: 'business',
    verified: true,
    about: 'A family dental practice. Takes one student intern each term at the front desk.',
    location: { city: 'Santa Clara', zip: '95051', lat: 37.3488, lng: -121.9836 },
  },
  {
    id: 'org-trailhead',
    name: 'Trailhead Parks Alliance',
    kind: 'nonprofit',
    verified: true,
    about: 'Looks after twelve miles of creek trail. Gloves, tools and water provided.',
    location: { city: 'Cupertino', zip: '95014', lat: 37.3229, lng: -122.0322 },
  },
  {
    id: 'org-nova',
    name: 'Nova Robotics Lab',
    kind: 'business',
    verified: true,
    about: 'A ten-person shop building inspection robots. Runs a paid summer intern track.',
    location: { city: 'Sunnyvale', zip: '94087', lat: 37.3524, lng: -122.0363 },
  },
  {
    id: 'org-mission',
    name: 'Mission Valley Youth Soccer',
    kind: 'nonprofit',
    verified: true,
    about: 'Weekend league for ages 5 to 12. Referees are paid per match and trained first.',
    location: { city: 'Santa Clara', zip: '95054', lat: 37.3924, lng: -121.9623 },
  },
  {
    id: 'org-lantern',
    name: 'The Lantern Bookshop',
    kind: 'business',
    verified: true,
    about: 'An independent bookshop with a small café at the back.',
    location: { city: 'Campbell', zip: '95008', lat: 37.2889, lng: -121.9432 },
  },
  {
    id: 'org-harborlight',
    name: 'Harborlight Senior Center',
    kind: 'nonprofit',
    verified: true,
    about: 'Day programmes, meals and a computer room for about 200 older neighbours.',
    location: { city: 'San Jose', zip: '95128', lat: 37.3138, lng: -121.9308 },
  },
  {
    id: 'org-quickstitch',
    name: 'Quickstitch Print Shop',
    kind: 'business',
    verified: false,
    about: 'Custom shirt and banner printing.',
    location: { city: 'San Jose', zip: '95112', lat: 37.3496, lng: -121.8841 },
  },
];

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-smoothie',
    organizationId: 'org-citrus',
    title: 'Smoothie Team Member',
    type: 'paid',
    status: 'PUBLISHED',
    minimumAge: 16,
    experience: 'none',
    timing: ['weekends', 'after_school'],
    hours: 'under_10',
    compensation: { kind: 'hourly', min: 20, max: 22 },
    summary: 'Make drinks, take orders and keep the front counter moving.',
    reassurance: 'Two shifts most weekends. Training provided, and this is a fine first job.',
    responsibilities: [
      'Blend drinks from the recipe cards',
      'Take orders at the counter and the pickup shelf',
      'Restock fruit and cups between rushes',
      'Wipe down the bar at close',
    ],
    schedule: 'Two shifts a week, mostly Saturday or Sunday, 11am–4pm. Some after-school shifts.',
    goodToKnow: ['Training provided', 'Free drink every shift', 'Shifts swap through a group chat'],
    interests: ['food', 'retail'],
    publishedAt: daysBack(2),
  },
  {
    id: 'opp-cinema-floor',
    organizationId: 'org-westgate',
    title: 'Box Office & Floor Crew',
    type: 'paid',
    status: 'PUBLISHED',
    minimumAge: 16,
    experience: 'none',
    timing: ['weekends', 'after_school'],
    hours: '10_20',
    compensation: { kind: 'hourly', min: 19 },
    summary: 'Sell tickets, tear stubs and reset theatres between showings.',
    reassurance: 'Busiest Friday and Saturday nights. No experience needed.',
    responsibilities: [
      'Sell tickets and answer questions about showtimes',
      'Check tickets at the door',
      'Reset seats and sweep between screenings',
      'Help at the snack counter when it is busy',
    ],
    schedule: 'Friday and Saturday evenings, plus one weekday afternoon if you want it.',
    goodToKnow: ['Free films on your days off', 'Uniform shirt provided', 'Paid every two weeks'],
    interests: ['retail', 'arts'],
    publishedAt: daysBack(5),
  },
  {
    id: 'opp-swim',
    organizationId: 'org-aquatics',
    title: 'Junior Swim Instructor',
    type: 'paid',
    status: 'PUBLISHED',
    minimumAge: 16,
    experience: 'some',
    timing: ['weekends', 'summer'],
    hours: '10_20',
    compensation: { kind: 'hourly', min: 23, max: 26 },
    summary: 'Teach beginner swim lessons to four- and five-year-olds alongside a lead coach.',
    reassurance: 'You need to be a confident swimmer. Everything else they teach you.',
    responsibilities: [
      'Run warm-ups with a group of four children',
      'Lead beginner drills the coach sets',
      'Keep eyes on the water the whole lesson',
      'Talk to parents at pickup',
    ],
    schedule: 'Saturday and Sunday mornings, 8am–1pm. Extra weekday hours over the summer.',
    goodToKnow: ['They pay for your lifeguard certification', 'Indoor heated pool', 'Free family swim'],
    interests: ['sports', 'kids', 'healthcare'],
    publishedAt: daysBack(9),
  },
  {
    id: 'opp-referee',
    organizationId: 'org-mission',
    title: 'Youth Soccer Referee',
    type: 'paid',
    status: 'PUBLISHED',
    minimumAge: 15,
    experience: 'none',
    timing: ['weekends'],
    hours: 'under_10',
    compensation: { kind: 'hourly', min: 28 },
    summary: 'Referee small-sided matches for ages 5 to 12 on Saturday mornings.',
    reassurance: 'Two Saturday mornings a month is enough. They train you first.',
    responsibilities: [
      'Referee two or three short matches in a morning',
      'Keep the game safe and moving',
      'Explain calls to players in plain words',
      'Hand the score sheet to the field marshal',
    ],
    schedule: 'Saturdays, 8am–12pm. You pick which weekends you are available.',
    goodToKnow: ['Paid training weekend before the season', 'Whistle and kit provided', 'Paid per match'],
    interests: ['sports', 'kids', 'outdoors'],
    publishedAt: daysBack(1),
  },
  {
    id: 'opp-bookshop',
    organizationId: 'org-lantern',
    title: 'Weekend Bookseller',
    type: 'paid',
    status: 'PUBLISHED',
    minimumAge: 16,
    experience: 'none',
    timing: ['weekends'],
    hours: 'under_10',
    compensation: { kind: 'hourly', min: 19, max: 20 },
    summary: 'Shelve new stock, work the till and help people find things.',
    reassurance: 'Quiet shop, steady pace. A good first job if you like being around books.',
    responsibilities: [
      'Unpack and shelve new arrivals',
      'Work the till and wrap gifts in December',
      'Help customers find a title',
      'Keep the front table looking tidy',
    ],
    schedule: 'One weekend day, 10am–4pm.',
    goodToKnow: ['30% staff discount', 'Free coffee from the café', 'Closed on major holidays'],
    interests: ['retail', 'arts', 'education'],
    publishedAt: daysBack(4),
  },
  {
    id: 'opp-shelter-care',
    organizationId: 'org-paws',
    title: 'Animal Care Volunteer',
    type: 'volunteer',
    status: 'PUBLISHED',
    minimumAge: 15,
    experience: 'none',
    timing: ['weekends', 'after_school', 'summer'],
    compensation: { kind: 'commitment', commitment: 'weekly' },
    summary: 'Feed, brush and sit with the cats so they stay used to people.',
    reassurance: 'One afternoon a week. Bring closed-toe shoes, that is the only rule.',
    responsibilities: [
      'Refill food and water in the cat room',
      'Brush and play with the shy ones',
      'Wash and fold bedding',
      'Write a short note on any animal that seems off',
    ],
    schedule: 'One three-hour shift a week, any afternoon Tuesday to Sunday.',
    goodToKnow: ['Counts toward service hours', 'Orientation is one Saturday morning', 'Closed-toe shoes required'],
    interests: ['animals', 'community'],
    publishedAt: daysBack(3),
  },
  {
    id: 'opp-food-pack',
    organizationId: 'org-bayline',
    title: 'Grocery Box Packing',
    type: 'volunteer',
    status: 'PUBLISHED',
    minimumAge: 15,
    experience: 'none',
    timing: ['weekends', 'winter_break', 'summer'],
    compensation: { kind: 'commitment', commitment: 'one_time' },
    summary: 'Pack grocery boxes on the warehouse line with a group.',
    reassurance: 'Come once or come every week. Groups and friends are welcome.',
    responsibilities: [
      'Pack boxes to the sheet on the wall',
      'Check dates on anything tinned',
      'Load finished boxes onto pallets',
      'Sweep the line at the end of the shift',
    ],
    schedule: 'Saturday mornings, 9am–12pm. Extra shifts over winter break.',
    goodToKnow: ['Service hours signed the same day', 'Water and snacks provided', 'Wear clothes you can move in'],
    interests: ['community', 'food'],
    publishedAt: daysBack(6),
  },
  {
    id: 'opp-trail',
    organizationId: 'org-trailhead',
    title: 'Creek Trail Restoration',
    type: 'volunteer',
    status: 'PUBLISHED',
    minimumAge: 15,
    experience: 'none',
    timing: ['weekends', 'spring_break'],
    compensation: { kind: 'commitment', commitment: 'monthly' },
    summary: 'Clear invasive plants and mulch new trees along the creek.',
    reassurance: 'Outdoor work, one Saturday a month. Tools and gloves are provided.',
    responsibilities: [
      'Pull invasive plants along a marked stretch',
      'Spread mulch around new trees',
      'Pick up litter near the water',
      'Help carry tools back to the trailer',
    ],
    schedule: 'The second Saturday of each month, 9am–1pm.',
    goodToKnow: ['Service hours provided', 'Gloves, tools and water provided', 'Cancelled if it rains hard'],
    interests: ['outdoors', 'community'],
    publishedAt: daysBack(12),
  },
  {
    id: 'opp-senior-tech',
    organizationId: 'org-harborlight',
    title: 'Tech Help Volunteer',
    type: 'volunteer',
    status: 'PUBLISHED',
    minimumAge: 15,
    experience: 'none',
    timing: ['after_school', 'weekends'],
    compensation: { kind: 'commitment', commitment: 'weekly' },
    summary: 'Sit with older neighbours and help them with phones, email and video calls.',
    reassurance: 'If you can set up a phone, you already know enough to do this.',
    responsibilities: [
      'Help with phones, tablets and email',
      'Set up video calls with family',
      'Write down the steps so they can do it again',
      'Be patient — the same question comes up twice',
    ],
    schedule: 'Tuesday or Thursday, 3pm–5pm.',
    goodToKnow: ['Service hours provided', 'Short training on your first visit', 'Tea and biscuits, always'],
    interests: ['technology', 'community', 'education'],
    publishedAt: daysBack(8),
  },
  {
    id: 'opp-dental-intern',
    organizationId: 'org-riverbend',
    title: 'Front Desk Intern',
    type: 'internship',
    status: 'PUBLISHED',
    minimumAge: 16,
    experience: 'none',
    timing: ['after_school'],
    hours: 'under_10',
    compensation: { kind: 'stipend', amount: 600, per: 'total' },
    summary: 'Learn how a dental practice runs from the front desk out.',
    reassurance: 'Built for someone thinking about healthcare. No experience expected.',
    responsibilities: [
      'Greet patients and check them in',
      'Confirm next-day appointments by phone',
      'Keep the waiting room stocked and tidy',
      'Shadow a hygienist one afternoon a week',
    ],
    schedule: 'Two afternoons a week, 3pm–6pm, for ten weeks.',
    goodToKnow: ['$600 stipend at the end', 'A reference letter if you finish', 'Scrubs provided'],
    interests: ['healthcare', 'business'],
    publishedAt: daysBack(7),
  },
  {
    id: 'opp-robotics-intern',
    organizationId: 'org-nova',
    title: 'Robotics Summer Intern',
    type: 'internship',
    status: 'PUBLISHED',
    minimumAge: 16,
    experience: 'some',
    timing: ['summer'],
    hours: '20_plus',
    compensation: { kind: 'hourly', min: 24 },
    summary: 'Work with the build team on test rigs and data collection.',
    reassurance: 'A robotics club or a class project is plenty of background.',
    responsibilities: [
      'Assemble and label test rigs',
      'Run the same test across ten units and log it',
      'Tidy up the data before the weekly review',
      'Sit in on the Monday planning meeting',
    ],
    schedule: 'Six weeks over the summer, Monday to Thursday, 10am–4pm.',
    goodToKnow: ['Lunch provided', 'You keep anything you build on the last day', 'Paid weekly'],
    interests: ['technology', 'business'],
    publishedAt: daysBack(11),
  },
  {
    id: 'opp-food-bank-intern',
    organizationId: 'org-bayline',
    title: 'Community Outreach Intern',
    type: 'internship',
    status: 'PUBLISHED',
    minimumAge: 16,
    experience: 'none',
    timing: ['after_school', 'summer'],
    hours: 'under_10',
    compensation: { kind: 'stipend', amount: 250, per: 'month' },
    summary: 'Help run the social accounts and the neighbourhood sign-up table.',
    reassurance: 'If you have run a club account, you have done most of this already.',
    responsibilities: [
      'Draft posts about upcoming distributions',
      'Photograph volunteer days',
      'Staff the sign-up table at weekend events',
      'Keep the contact list current',
    ],
    schedule: 'Two afternoons a week plus one Saturday a month.',
    goodToKnow: ['$250 a month stipend', 'Reference letter after three months', 'Bus line stops outside'],
    interests: ['community', 'arts', 'business'],
    publishedAt: daysBack(3),
  },
  {
    id: 'opp-cinema-projection',
    organizationId: 'org-westgate',
    title: 'Projection Booth Assistant',
    type: 'paid',
    status: 'PUBLISHED',
    minimumAge: 17,
    experience: 'some',
    timing: ['weekends', 'after_school'],
    hours: 'under_10',
    compensation: { kind: 'hourly', min: 21 },
    summary: 'Load features, run the projector schedule and watch for sound faults.',
    reassurance: 'You will be trained on the equipment over two paid shifts.',
    responsibilities: [
      'Build the evening schedule in the projection system',
      'Check focus and sound at the start of each screening',
      'Log any fault for the technician',
      'Close the booth down at end of night',
    ],
    schedule: 'Friday and Saturday evenings, 5pm–11pm.',
    goodToKnow: ['Two paid training shifts', 'Free films on your days off', 'You need to stay until close'],
    interests: ['technology', 'arts'],
    publishedAt: daysBack(14),
  },
  {
    id: 'opp-shelter-events',
    organizationId: 'org-paws',
    title: 'Adoption Day Helper',
    type: 'volunteer',
    status: 'PUBLISHED',
    minimumAge: 15,
    experience: 'none',
    timing: ['weekends'],
    compensation: { kind: 'commitment', commitment: 'one_time' },
    summary: 'Set up the adoption tent, greet families and hand out forms.',
    reassurance: 'One Sunday a month. Perfect if you want to help without a weekly commitment.',
    responsibilities: [
      'Set up tents, pens and signage',
      'Greet families and explain how adoption works',
      'Hand out and collect forms',
      'Pack everything back into the van',
    ],
    schedule: 'The last Sunday of the month, 10am–3pm.',
    goodToKnow: ['Service hours provided', 'Lunch provided', 'Outdoors in all weather'],
    interests: ['animals', 'community', 'kids'],
    publishedAt: daysBack(2),
  },
  {
    id: 'opp-swim-desk',
    organizationId: 'org-aquatics',
    title: 'Front Desk & Check-In',
    type: 'paid',
    status: 'PUBLISHED',
    minimumAge: 15,
    experience: 'none',
    timing: ['weekends', 'after_school'],
    hours: 'under_10',
    compensation: { kind: 'hourly', min: 18, max: 19 },
    summary: 'Check families in for lessons and answer the phone.',
    reassurance: 'The quietest job in the building, and a good place to start at 15.',
    responsibilities: [
      'Check families in on the tablet',
      'Answer the phone and take messages',
      'Hand out towels and lost property',
      'Keep the lobby tidy',
    ],
    schedule: 'Saturday mornings plus one weekday afternoon.',
    goodToKnow: ['Training provided', 'Free swim lessons for staff', 'Indoors and warm'],
    interests: ['sports', 'kids', 'retail'],
    publishedAt: daysBack(1),
  },
  {
    id: 'opp-camp-counselor',
    organizationId: 'org-mission',
    title: 'Summer Camp Counsellor',
    type: 'paid',
    status: 'PUBLISHED',
    minimumAge: 16,
    experience: 'none',
    timing: ['summer'],
    hours: '20_plus',
    compensation: { kind: 'hourly', min: 20 },
    summary: 'Run games and drills for a group of eight children for six weeks.',
    reassurance: 'Coaching a younger sibling counts as experience here.',
    responsibilities: [
      'Lead a group of eight through the daily schedule',
      'Run warm-ups and small-sided games',
      'Keep track of water breaks and sunscreen',
      'Hand children over to parents at pickup',
    ],
    schedule: 'Six weeks in summer, Monday to Friday, 8:30am–3pm.',
    goodToKnow: ['Paid training week', 'Lunch provided', 'Kit and whistle provided'],
    interests: ['sports', 'kids', 'outdoors'],
    publishedAt: daysBack(16),
  },
  {
    id: 'opp-senior-meals',
    organizationId: 'org-harborlight',
    title: 'Lunch Service Volunteer',
    type: 'volunteer',
    status: 'PUBLISHED',
    minimumAge: 15,
    experience: 'none',
    timing: ['weekends', 'summer', 'winter_break'],
    compensation: { kind: 'commitment', commitment: 'weekly' },
    summary: 'Serve lunch and sit with people while they eat.',
    reassurance: 'Two hours a week. The talking matters more than the serving.',
    responsibilities: [
      'Set the tables before service',
      'Serve plates and refill drinks',
      'Sit and talk with anyone eating alone',
      'Clear and wipe down afterwards',
    ],
    schedule: 'Saturdays, 11am–1pm.',
    goodToKnow: ['Service hours provided', 'Hairnet and apron provided', 'You eat with everyone else'],
    interests: ['community', 'food', 'healthcare'],
    publishedAt: daysBack(10),
  },
  {
    id: 'opp-shift-lead',
    organizationId: 'org-citrus',
    title: 'Weekend Shift Lead',
    type: 'paid',
    status: 'PUBLISHED',
    minimumAge: 18,
    experience: 'required',
    timing: ['weekends'],
    hours: '10_20',
    compensation: { kind: 'hourly', min: 24, max: 26 },
    summary: 'Open or close the store and run the weekend crew.',
    reassurance: 'For someone who has already worked a counter job.',
    responsibilities: [
      'Open or close the store',
      'Set the shift plan for three or four people',
      'Count the till',
      'Handle anything a customer escalates',
    ],
    schedule: 'Saturday and Sunday, one opening and one closing shift.',
    goodToKnow: ['Key-holder responsibility', 'Higher weekend rate', 'Six months of counter work expected'],
    interests: ['food', 'business', 'retail'],
    publishedAt: daysBack(13),
  },
  {
    id: 'opp-lantern-cafe',
    organizationId: 'org-lantern',
    title: 'Café Counter Help',
    type: 'paid',
    status: 'PUBLISHED',
    minimumAge: 17,
    experience: 'some',
    timing: ['weekends', 'after_school'],
    hours: 'under_10',
    compensation: { kind: 'hourly', min: 20 },
    summary: 'Make coffee, warm pastries and clear the café tables.',
    reassurance: 'They will teach you the machine. Being steady matters more than being fast.',
    responsibilities: [
      'Make coffee and tea to order',
      'Warm and plate pastries',
      'Clear and wipe tables',
      'Restock milk and cups',
    ],
    schedule: 'Two shifts a week, afternoons and weekend mornings.',
    goodToKnow: ['Barista training over two shifts', 'Staff discount on books', 'Tips split evenly'],
    interests: ['food', 'arts'],
    publishedAt: daysBack(20),
  },
  {
    id: 'opp-trail-lead',
    organizationId: 'org-trailhead',
    title: 'Volunteer Crew Lead',
    type: 'volunteer',
    status: 'PUBLISHED',
    minimumAge: 17,
    experience: 'required',
    timing: ['weekends'],
    compensation: { kind: 'commitment', commitment: 'monthly' },
    summary: 'Lead a small crew on a restoration stretch.',
    reassurance: 'For someone who has already done a few trail days with a group.',
    responsibilities: [
      'Brief a crew of six on the day',
      'Keep everyone to the marked stretch',
      'Check tools in and out',
      'Report what got done to the site manager',
    ],
    schedule: 'The second Saturday of each month, 8am–2pm.',
    goodToKnow: ['Service hours provided', 'Leadership training day first', 'Radio provided'],
    interests: ['outdoors', 'community'],
    publishedAt: daysBack(18),
  },
  {
    id: 'opp-print-shop',
    organizationId: 'org-quickstitch',
    title: 'Print Shop Assistant',
    type: 'paid',
    status: 'PENDING_REVIEW',
    minimumAge: 16,
    experience: 'none',
    timing: ['after_school'],
    hours: 'under_10',
    compensation: { kind: 'hourly', min: 18 },
    summary: 'Help with heat pressing and packing orders.',
    reassurance: 'Training provided.',
    responsibilities: ['Heat press shirts', 'Pack and label orders'],
    schedule: 'Weekday afternoons.',
    goodToKnow: ['Training provided'],
    interests: ['retail', 'arts'],
    publishedAt: daysBack(1),
  },
];

/* What an organization sees once a student has expressed interest — and not
   one field before that. No address, no exact date of birth, no surname. */
export const INTERESTED_STUDENTS: Record<string, InterestedStudent[]> = {
  'opp-smoothie': [
    {
      id: 'stu-1',
      firstName: 'Maya',
      age: 16,
      city: 'Santa Clara',
      distanceMiles: 2.3,
      availability: ['weekends', 'after_school'],
      interests: ['food', 'community'],
      experience: 'First job',
      note: 'I like that it is close enough to bike and I already know the menu.',
    },
    {
      id: 'stu-2',
      firstName: 'Devin',
      age: 17,
      city: 'Santa Clara',
      distanceMiles: 1.1,
      availability: ['weekends'],
      interests: ['food', 'sports'],
      experience: 'Some experience',
      note: 'I worked a concession stand at the pool last summer.',
    },
    {
      id: 'stu-3',
      firstName: 'Priya',
      age: 16,
      city: 'Sunnyvale',
      distanceMiles: 4.4,
      availability: ['after_school'],
      interests: ['food', 'business'],
      experience: 'First job',
    },
  ],
  'opp-referee': [
    {
      id: 'stu-4',
      firstName: 'Noah',
      age: 15,
      city: 'Santa Clara',
      distanceMiles: 3.0,
      availability: ['weekends'],
      interests: ['sports', 'outdoors'],
      experience: 'First job',
      note: 'I have played in this league since I was seven.',
    },
    {
      id: 'stu-5',
      firstName: 'Ana',
      age: 16,
      city: 'Santa Clara',
      distanceMiles: 2.1,
      availability: ['weekends', 'summer'],
      interests: ['sports', 'kids'],
      experience: 'Some experience',
    },
  ],
};

/* Rough catchment figures used to tell an employer how many students a
   posting would actually reach. Always shown hedged with "about" — it is an
   estimate from the student base, not a promise of applicants. */
export const STUDENTS_NEARBY: Record<string, number> = {
  'Santa Clara': 420,
  'San Jose': 980,
  Campbell: 210,
  Sunnyvale: 390,
  Cupertino: 260,
  'Mountain View': 240,
  Milpitas: 280,
  Saratoga: 140,
  'Los Gatos': 160,
};

/* Each extra year of minimum age cuts the eligible pool. Roughly a third of
   the high-school population sits in each band. */
export function estimateReach(city: string, minimumAge: number): number {
  const base = STUDENTS_NEARBY[city] ?? 300;
  const share = { 15: 1, 16: 0.76, 17: 0.5, 18: 0.24 }[minimumAge] ?? 0.5;
  return Math.round((base * share) / 10) * 10;
}
